name: First workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: windows-latest
        steps:
            - name: echo a string
              run: echo "Hello World!"
            - name: multiline commands
              run:
                node -v
                npm -v