name: workflow-commands
on: [push]

jobs:
    testing-workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error message with params
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a debug message
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: Setting a warning message
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: group of logs
              run:
                echo "::group::My group title"
                echo "::endgroup::"